spring:
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: pool
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: teste
      password: teste
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect