adapter:
  aws:
    access-key: ${AWS_ACCESS_KEY:ADMIN}
    secret-key: ${AWS_SECRET_KEY:ADMIN}
    open-search:
      url: ${AWS_OPEN_SEACRH_URL:localhost:9200}
    s3:
      bucket-name: ${BUCKET_NAME:flash-pet-images}
  cache-size: ${CACHE_SIZE:1000}
  cache-duration: ${CACHE_DURATION:2}
