swagger: '2.0'
info:
  description: This is api rest contract
  version: 1.0.0
  title: Swagger FlashPet
basePath: /v1
tags:
  - name: company
    description: Everything about your Pets
  - name: service
    description: Access to Petstore orders
schemes:
  - https
  - http
paths:
  /companies:
    post:
      tags:
        - company
      summary: Add a new company
      description: ''
      operationId: addCompany
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Company'
      responses:
        '201':
          description: Company saved
          schema:
            $ref: '#/definitions/Company'
        '405':
          description: Invalid input
          schema:
            $ref: '#/definitions/ApiResponse'
    put:
      tags:
        - company
      summary: Update an existing Company
      description: ''
      operationId: updateCompany
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Company'
      responses:
        '200':
          description: Company updated
          schema:
            $ref: '#/definitions/Company'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Company not found
          schema:
            $ref: '#/definitions/ApiResponse'
        '405':
          description: Validation exception
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      tags:
        - company
      parameters:
        - in: query
          name: page_number
          required: true
          type: integer
        - in: query
          name: service_description
          type: string
        - in: query
          name: price_category
          type: string
          enum:
            - low_100_300
            - low_max_100_1000
      summary: Finds all companies
      operationId: findCompanies
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Company'
        '400':
          description: Invalid status value
          schema:
            $ref: '#/definitions/ApiResponse'
definitions:
  Company:
    type: object
    properties:
      id:
        type: string
        format: string
      name:
        type: string
        format: string
      address:
        type: string
        format: string
      services:
        type: array
        items:
          $ref: '#/definitions/Service'
  Service:
    type: object
    properties:
      id:
        type: string
        format: string
      description:
        type: string
        example: Service to shower your pet
      price:
        type: number
        format: double
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string