swagger: '2.0'
info:
  description: This is api rest contract
  version: 1.0.0
  title: Swagger FlashPet
basePath: /v1
tags:
  - name: company
    description: Everything about your Pets
  - name: service
    description: Access to Petstore orders
  - name: auth
    description: Auth service
schemes:
  - https
  - http
paths:
  /companies:
    post:
      tags:
        - company
      summary: Add a new company
      description: ''
      operationId: addCompany
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Company'
      responses:
        '201':
          description: Company saved
          schema:
            $ref: '#/definitions/Company'
        '405':
          description: Invalid input
          schema:
            $ref: '#/definitions/ModelApiResponse'
    put:
      tags:
        - company
      summary: Update an existing Company
      description: ''
      operationId: updateCompany
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Company'
      responses:
        '200':
          description: Company updated
          schema:
            $ref: '#/definitions/Company'
        '400':
          description: Invalid ID supplied
          schema:
            $ref: '#/definitions/ModelApiResponse'
        '404':
          description: Company not found
          schema:
            $ref: '#/definitions/ModelApiResponse'
        '405':
          description: Validation exception
          schema:
            $ref: '#/definitions/ModelApiResponse'
    get:
      tags:
        - company
      parameters:
        - in: query
          name: service_description
          type: string
        - in: query
          name: price_category
          type: string
          enum:
            - low_000_300
            - midlle_300_600
            - high_600_up
        - in: query
          name: service_type
          type: string
          enum:
            - bath_shear
            - vaccinate
            - medical_consultation
            - surgery
            - host
        - in: query
          name: latitude
          type: number
          format: double
        - in: query
          name: longitude
          type: number
          format: double
      summary: Finds all companies
      operationId: findCompanies
      produces:
        - application/json
      responses:
        '200':
          headers:
            X-Sroll-id:
              type: string
              description: scroll id.
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Company'
        '400':
          description: Invalid status value
          schema:
            $ref: '#/definitions/ModelApiResponse'

  /companies/{scroll}:
    get:
      tags:
        - company
      parameters:
        - in: path
          name: scroll
          type: string
          required: true
      summary: Finds all companies
      operationId: findCompaniesByScroll
      produces:
        - application/json
      responses:
        '200':
          headers:
            X-Sroll-id:
              type: string
              description: scroll id.
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Company'
        '400':
          description: Invalid status value
          schema:
            $ref: '#/definitions/ModelApiResponse'

  /authenticate:
    post:
      tags:
        - auth
      summary: Endpoint to get jwt token
      description: ''
      operationId: auth
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Jwt_Request'
      responses:
        '200':
          description: Jwt generated
          schema:
            $ref: '#/definitions/Jwt_Response'
        '405':
          description: Invalid input
          schema:
            $ref: '#/definitions/ModelApiResponse'


definitions:
  Company:
    type: object
    properties:
      id:
        type: string
        format: string
      name:
        type: string
        format: string
      address:
        type: string
        format: string
      latitude:
        type: number
        format: double
      longitude:
        type: number
        format: double
      services:
        type: array
        items:
          $ref: '#/definitions/Service'

  Service:
    type: object
    properties:
      id:
        type: string
        format: string
      description:
        type: string
        example: Service to shower your pet
      price:
        type: number
        format: double

  Jwt_Request:
    type: object
    properties:
      username:
        type: string
        format: string
      password:
        type: string
        format: string

  Jwt_Response:
    type: object
    properties:
      token:
        type: string
        format: string

  ModelApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string